services:
  nextjs:
    build: .
    container_name: app-sample
    restart: always
    ports:
      - "3000:3000"
    environment:
      - APP_ENV=${APP_ENV}
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/app
      - /app/node_modules
    labels:
      - "traefik.enable=${TRAERFIK_ENABLED}"
      - "traefik.http.routers.app-sample.rule=Host(`sample.takumi-shinzato.com`)"
      - "traefik.http.routers.app-sample.entrypoints=websecure"
      - "traefik.http.routers.app-sample.tls.certresolver=letsencrypt"
    networks:
      - app-network

networks:
  app-network:
    external: true